import { useState } from "react";
import { ArrowLeft, Check, Moon, Sparkles, Sun, UserRound } from "lucide-react";
import "./SettingsPage.css";

function SettingsPage({ setActiveTab, user, theme, setTheme }) {
  const [activeSection, setActiveSection] = useState("Profile");
  const [saved, setSaved] = useState(false);
  const themes = [{ id: "light", label: "Light", Icon: Sun }, { id: "dark", label: "Dark", Icon: Moon }, { id: "yellow", label: "Warm", Icon: Sparkles }];
  const save = () => { localStorage.setItem("ai-cert-theme", theme); setSaved(true); window.setTimeout(() => setSaved(false), 2200); };
  return <div className="settings-page"><header className="settings-header"><div><h1>Settings</h1><p className="subtitle">Review your local account and display preferences.</p></div><button className="back-results-btn" type="button" onClick={() => setActiveTab("Home")}><ArrowLeft aria-hidden="true" />Back to Dashboard</button></header><div className="settings-layout"><div className="settings-sidebar" role="tablist" aria-label="Settings sections">{["Profile", "Preferences"].map((tab) => <button key={tab} type="button" role="tab" aria-selected={activeSection === tab} className={`settings-tab ${activeSection === tab ? "active" : ""}`} onClick={() => setActiveSection(tab)}>{tab}</button>)}</div><div className="settings-content">{activeSection === "Profile" ? <section className="settings-card"><div className="profile-summary"><span className="profile-summary-icon"><UserRound aria-hidden="true" /></span><div><h2>{user.full_name}</h2><p>{user.email}</p></div></div><div className="settings-form-grid"><div className="form-group"><label htmlFor="profile-name">Full name</label><input id="profile-name" type="text" value={user.full_name} readOnly /></div><div className="form-group"><label htmlFor="profile-email">Email address</label><input id="profile-email" type="email" value={user.email} readOnly /></div></div><p className="settings-note">Profile editing and password management will be added with the production security phase. Your password is already stored as an Argon2 hash, never plaintext.</p></section> : <section className="settings-card"><h2>Display Preferences</h2><p className="section-desc">Choose a theme for this browser.</p><fieldset className="theme-choice-grid"><legend>Color theme</legend>{themes.map(({ id, label, Icon }) => <button key={id} type="button" aria-pressed={theme === id} className={`theme-choice ${theme === id ? "active" : ""}`} onClick={() => setTheme(id)}><Icon aria-hidden="true" /><span>{label}</span>{theme === id && <Check className="theme-check" aria-hidden="true" />}</button>)}</fieldset><div className="settings-save-bar">{saved && <span className="saved-indicator" role="status"><Check aria-hidden="true" />Preferences saved</span>}<button className="save-settings-btn" type="button" onClick={save}>Save Preferences</button></div></section>}</div></div></div>;
}
export default SettingsPage;

